### PR TITLE
fix: remove empty field in the releaser configuration.

### LINKED ISSUE #1829: Fail to build locally
I'm new in the project and trying to build everything locally. After running the command `go run ./dagger --setup` and following the input requests I've ended with the following file

```yaml
charts:
    git:
        auth:
            email: ""
            username: ""
        branch: ""
        export: false
        push: false
        repo: ghcr.io/jvanz
    oci:
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
coverage:
    export: false
images:
    minimal:
        additional-tags: []
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
        tag: latest
        tag-suffix: -minimal
    opensearch:
        build:
            dashboards-version: 2.8.0
            opensearch-version: 2.8.0
            plugin-version: 0.12.0
        dashboards:
            additional-tags: []
            auth:
                email: ""
                username: ""
            push: false
            repo: ghcr.io/jvanz
            tag: latest
            tag-suffix: ""
        opensearch:
            additional-tags: []
            auth:
                email: ""
                username: ""
            push: false
            repo: ghcr.io/jvanz
            tag: latest
            tag-suffix: ""
        update-service:
            additional-tags: []
            auth:
                email: ""
                username: ""
            push: false
            repo: ghcr.io/jvanz
            tag: latest
            tag-suffix: ""
    opni:
        additional-tags: []
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
        tag: latest
        tag-suffix: ""
    python-base:
        additional-tags: []
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
        tag: latest
        tag-suffix: ""
    python-torch:
        additional-tags: []
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
        tag: latest
        tag-suffix: -torch
lint: false
releaser:
    arch: []
    auth:
        email: ""
        username: ""
    os: []
    push: false
    repo: ghcr.io/jvanz
    tag: latest
test: true
```

However, when I ran the command `dagger run go run ./dagger -c dagger/ci/defaults,dev/dagger --charts.git.export` it failed:

```
$ dagger run go run ./dagger -c dagger/ci/defaults,dev/dagger.yaml --charts.git.export
┣─╮ 
│ ▽ init
│ █ [1.11s] connect
│ ┣ [0.86s] starting engine
│ ┣ [0.21s] starting session
│ ┻ 
█ [0.60s] ERROR go run ./dagger -c dagger/ci/defaults,dev/dagger.yaml --charts.git.export
┃ incorrect types at key os, type []string != []interface {}                                                                                                                                                                                  
┃ exit status 1                                                                                                                                                                                                                               
┻ 
• Engine: 89e85dd7b6f0 (version v0.8.7)
⧗ 1.71s ✔ 3 ✘ 1
```

Turns out that the generated file has the fields `releaser.os` and `releaser.arch` empty values. Which causes the command to fail. Even the `--show-config` command fail with the same error.  I've tested with generated fails using `yaml` and `toml` format.

To workaround this issue, I must have to remove the `releaser.os` and `releaser.arch` fields from the generated file.

### PR DESCRIPTION
**Pull request by jvanz**
The setup command is writing a file with the `releaser.os` and `releaser.arch` fields as empty lists. This is causing problems in the merge of the default configuration and the configuration generated by the command. During the merge the fields from the files are considered different types causing a failure. As the generate file should be used to overwrite the default values does not make sense to write a file with a invalid field value (empty list). Therefore, this commit change the setup command to remove the mentioned field from the file when they are empty.

Fix #1829

### CODE REVIEW

File: dagger/config/config.go [hunk 1]
```diff
@@ -214,8 +214,7 @@ func mergeStrict(src, dest map[string]any) error {
 				// Handle the special case where empty slices are decoded as []any causing
 				// a type mismatch when merging with a slice of a specific type.
 				if reflect.TypeOf(dest[key]).Kind() == reflect.Slice &&
-					reflect.TypeOf(val) == reflect.TypeOf(([]any)(nil)) &&
```
Comment (jvanz) [inline dagger/config/config.go:217]: Related to https://github.com/rancher/opni/issues/1829#issuecomment-1802414861

File: dagger/config/config.go [hunk 2]
```diff
@@ -214,8 +214,7 @@ func mergeStrict(src, dest map[string]any) error {
...
-					reflect.ValueOf(dest[key]).Len() == 0 {
```
Comment (jvanz) [inline dagger/config/config.go:218]: Related to https://github.com/rancher/opni/issues/1829#issuecomment-1802414861

**Comment by jvanz** [comment]
Instead of changing the `--setup` command the merge function has been updated to properly merge the configs when an empty slice is found.
