### PR TITLE
Fix delete of old Opensearch data

### LINKED ISSUE #1353: Delete data does not remove data from warm indices
When ISM rolls over the index it forces it into read only mode.  This stops the delete_by_query from deleting data from warm indices.

@AmartC FYI

### PR DESCRIPTION
**Pull request by dbason**
Fixes #1353

### CODE REVIEW

File: plugins/logging/pkg/opensearchdata/delete.go [hunk 1]
```diff
@@ -148,3 +148,19 @@ func (m *Manager) DeleteTaskStatus(ctx context.Context, id string, readyFunc ...
 
 	return DeleteFinished, nil
 }
+
+func (m *Manager) DeleteKVKey(ctx context.Context, id string) error {
```
Comment (kralicky) [inline plugins/logging/pkg/opensearchdata/delete.go:152]: this seems a bit too hacky :stuck_out_tongue:

**Review by kralicky — DISMISSED** [review]

**Review by kralicky — APPROVED** [review]
