### PR TITLE
Various logging fixes

### LINKED ISSUE #1695: Logging Backend v0.11.1 install fails when both ephemeral storage and a single Primary Pod are configured
Logging Backend install using v0.11.1 fails when both ephemeral storage and a single Primary Pod are configured. The specific error is included below:

[403 Forbidden] {"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [cluster:monitor/task/get] and User [name=internalopni, backend_roles=[], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [cluster:monitor/task/get] and User [name=internalopni, backend_roles=[], requestedTenant=null]"},"status":403}: opensearch request unsuccessful

### LINKED ISSUE #1700: Panic reconfiguring v0.11.1 Logging Backend to have 3 persistent replicas instead of 3 ephemeral replicas
The following panic was encountered when I attempted to reconfigure the v0.11.1 Logging Backend to have 3 persistent replicas instead of 3 ephemeral replicas:

```
[04:08:04] INFO Generating certificates {"controller": "opensearchcluster", "controllerGroup": "[opensearch.opster.io](http://opensearch.opster.io/)", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"opni","namespace":"opni"}, "namespace": "opni", "name": "opni", "reconcileID": "11a160f3-966e-4979-b16f-b5848f1a51a6", "interface": "http"}
[04:08:04] INFO updating existing ism {"controller": "multiclusterrolebinding", "controllerGroup": "[logging.opni.io](http://logging.opni.io/)", "controllerKind": "MulticlusterRoleBinding", "MulticlusterRoleBinding": {"name":"opni","namespace":"opni"}, "namespace": "opni", "name": "opni", "reconcileID": "c3431a0e-56c2-4e53-b119-21012136273a", "policy": "log-policy"}
[04:08:04] INFO Observed a panic in reconciler: runtime error: index out of range [0] with length 0 {"controller": "opensearchcluster", "controllerGroup": "[opensearch.opster.io](http://opensearch.opster.io/)", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"opni","namespace":"opni"}, "namespace": "opni", "name": "opni", "reconcileID": "11a160f3-966e-4979-b16f-b5848f1a51a6"}
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0
goroutine 880 [running]:
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1())
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115) +0x1e5
panic({0x488cea0?, 0xc003f9b260?})
        runtime/panic.go:914 +0x21f
[opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).reconcileNodeStatefulSet(_](http://opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).reconcileNodeStatefulSet(_), {{0xc001b3818c, 0x4}, 0x3, {0xc001b38190, 0x4}, {0xc0016ffc20, 0xc0016ffc50, {0x0, 0x0, ...}}, ...}, ...)
        opensearch.opster.io@v0.0.0-00010101000000-000000000000/pkg/reconcilers/cluster.go:308 +0x1f18
[opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).Reconcile(0xc00046abd0)](http://opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).Reconcile(0xc00046abd0))
        opensearch.opster.io@v0.0.0-00010101000000-000000000000/pkg/reconcilers/cluster.go:120 +0x9b0
[opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).reconcilePhaseRunning(0xc001030a50](http://opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).reconcilePhaseRunning(0xc001030a50), {0x63c5490, 0xc0016ff890})
        opensearch.opster.io@v0.0.0-00010101000000-000000000000/controllers/opensearchController.go:320 +0x7ad
[opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).Reconcile(0xc001030a50](http://opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).Reconcile(0xc001030a50), {0x63c5490, 0xc0016ff890}, {{{0xc001b380e4, 0x4}, {0xc001b380e0, 0x4}}})
        opensearch.opster.io@v0.0.0-00010101000000-000000000000/controllers/opensearchController.go:141 +0x779
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x63c5490](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x63c5490)?, {0x63c5490?, 0xc0016ff890?}, {{{0xc001b380e4?, 0x40b50a0?}, {0xc001b380e0?, 0x6399528?}}})
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118) +0xb7
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000fafb80](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000fafb80), {0x63c54c8, 0xc000f65860}, {0x45f69c0?, 0xc001b8c020?})
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314) +0x365
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000fafb80](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000fafb80), {0x63c54c8, 0xc000f65860})
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265) +0x1c9
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2())
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226) +0x79
created by [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2) in goroutine 375
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222) +0x565
```

### PR DESCRIPTION
**Pull request by dbason**
Fixes #1700
Fixes #1695

### CODE REVIEW

File: plugins/logging/pkg/errors/errors.go [hunk 1]
```diff
@@ -11,6 +11,7 @@ import (
 var (
 	ErrInvalidList             = utilerrors.New(codes.FailedPrecondition, errors.New("list did not return exactly 1 result"))
 	ErrInvalidPersistence      = utilerrors.New(codes.InvalidArgument, errors.New("invalid persistence config"))
+	ErrInvalidDataPersistence  = utilerrors.New(codes.InvalidArgument, errors.New("minimum of 2 data nodes required if no persistent storage"))
```
Comment (kralicky) [inline plugins/logging/pkg/errors/errors.go:14]: Should this message match the other one?

Comment (dbason) [reply plugins/logging/pkg/errors/errors.go:14]: Nope, this is technically a different error state.  The first one is for if there is a mismatch or misconfiguration in the actual persistence settings.  In this error the settings are technically valid (or non existent) but lead to an unsafe cluster configuration.

Comment (kralicky) [reply plugins/logging/pkg/errors/errors.go:14]: Sorry I was referring to the wording between this error and the other log message in this PR

**Review by kralicky — APPROVED** [review]
