### PR TITLE
Fix import progress timestamp

### LINKED ISSUE #1375: Panic encountered while watching data import progress:
Panic encountered while watching data import progress:

```
2023-05-03T14:51:55Z INFO commands/import.go:326 import started

  █████████████████████████████████████████████████████████████████████░░░░░░  92%

  State: running
  Last Read Timestamp: 2023-05-03 14:36:55 +0000 UTC
  Message: import running

Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        github.com/charmbracelet/bubbletea@v0.23.2/tea.go:402 +0x95
panic({0x3e6c6e0, 0xf406470})
        runtime/panic.go:890 +0x263
github.com/rancher/opni/pkg/opni/commands.ProgressModel.Update({{0xce70b98, 0xc0015965f0}, 0xc000af48d0, 0x0, {0x1, 0x0, 0x50, 0x2588, {0x0, 0x0}, ...}, ...}, ...)
        github.com/rancher/opni/pkg/opni/commands/import_progress.go:129 +0x257
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc001437760, {0xce6e190?, 0xc001438b00?}, 0x3c47f60?)
        github.com/charmbracelet/bubbletea@v0.23.2/tea.go:343 +0x60a
github.com/charmbracelet/bubbletea.(*Program).Run(0xc001437760)
        github.com/charmbracelet/bubbletea@v0.23.2/tea.go:465 +0x7fd
github.com/charmbracelet/bubbletea.(*Program).Start(...)
        github.com/charmbracelet/bubbletea@v0.23.2/tea.go:507
github.com/rancher/opni/pkg/opni/commands.followProgress({0xce70b98, 0xc0015965f0}, {0x7ffefb27aea6, 0x4}, {0x7ffefb27ae81, 0x24})
        github.com/rancher/opni/pkg/opni/commands/import.go:67 +0x16a
github.com/rancher/opni/pkg/opni/commands.BuildImportStartCmd.func2(0xc0015ba900, {0xc0015d0780, 0x2, 0x3?})
        github.com/rancher/opni/pkg/opni/commands/import.go:329 +0x557
github.com/spf13/cobra.(*Command).execute(0xc0015ba900, {0xc0015d0720, 0x3, 0x3})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0015e5b00)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.7.0/command.go:985
github.com/rancher/opni/pkg/opni.Execute()
        github.com/rancher/opni/pkg/opni/root.go:37 +0x7f
main.main()
        github.com/rancher/opni/cmd/opni/main.go:10 +0x5a
```

### PR DESCRIPTION
**Pull request by jan-law**
Closes #1375

### CODE REVIEW

File: pkg/opni/commands/import_progress.go [hunk 1]
```diff
@@ -38,12 +38,8 @@ func getNextStatus(ctx context.Context, request *remoteread.TargetStatusRequest)
...
 
 func getProgressAsPercent(progress *remoteread.TargetProgress) float64 {
-	if progress == nil || progress.LastReadTimestamp == nil {
-		return 0
-	}
-
-	percent := float64(progress.LastReadTimestamp.Seconds-progress.StartTimestamp.Seconds) /
-		float64(progress.EndTimestamp.Seconds-progress.StartTimestamp.Seconds)
+	percent := float64(progress.GetLastReadTimestamp().GetSeconds()-progress.GetStartTimestamp().GetSeconds()) /
+		float64(progress.GetEndTimestamp().GetSeconds()-progress.GetStartTimestamp().GetSeconds())
```
Comment (kralicky) [inline pkg/opni/commands/import_progress.go:42]: Need a check to prevent dividing by zero here

File: pkg/opni/commands/import_progress.go [hunk 2]
```diff
@@ -126,7 +125,7 @@ func (model ProgressModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
 		}
 
 		model.percent = getProgressAsPercent(msg.Progress)
-		model.lastRead = msg.Progress.LastReadTimestamp
+		model.lastRead = msg.GetProgress().GetLastReadTimestamp()
```
Comment (joshmeranda) [inline pkg/opni/commands/import_progress.go:128]: if `msg.GetProgress()` returns nil this'll panic. Typically this won't be an issue but see https://github.com/rancher/opni/blob/main/plugins/metrics/pkg/agent/runner.go#L399 and https://github.com/rancher/opni/blob/main/plugins/metrics/pkg/agent/runner.go#L404

**Review by joshmeranda — CHANGES_REQUESTED** [review]

File: pkg/opni/commands/import_progress.go (hunk 1 above)
Comment (jan-law) [reply pkg/opni/commands/import_progress.go]: whoops thanks

**Review by joshmeranda — DISMISSED** [review]

**Review by kralicky — APPROVED** [review]
